#!/bin/bash

sudo cp ./fruitywatch /usr/local/bin 

## cd && echo 'watch -tcpn.5 '\''figlet -f big -W "$(date +%l:%M:%S)"|toilet -f term --gay'\' > fruitywatch && chmod +x fruitywatch; mv ./fruitywatch /usr/local/bin && fruitywatch

## todo:  this installer sucks.  
